/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as UiComponentsRouteImport } from './routes/ui-components'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegexFiltersRouteImport } from './routes/regex-filters'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as LongTermRouteImport } from './routes/long-term'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalDnsRouteImport } from './routes/local-dns'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DisableRouteImport } from './routes/disable'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BlockPageSettingsRouteImport } from './routes/block-page-settings'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AllowlistRouteImport } from './routes/allowlist'
import { Route as AdlistsRouteImport } from './routes/adlists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsClientIpStatsRouteImport } from './routes/clients.$clientIp.stats'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const UiComponentsRoute = UiComponentsRouteImport.update({
  id: '/ui-components',
  path: '/ui-components',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexFiltersRoute = RegexFiltersRouteImport.update({
  id: '/regex-filters',
  path: '/regex-filters',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const LongTermRoute = LongTermRouteImport.update({
  id: '/long-term',
  path: '/long-term',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalDnsRoute = LocalDnsRouteImport.update({
  id: '/local-dns',
  path: '/local-dns',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DisableRoute = DisableRouteImport.update({
  id: '/disable',
  path: '/disable',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockPageSettingsRoute = BlockPageSettingsRouteImport.update({
  id: '/block-page-settings',
  path: '/block-page-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowlistRoute = AllowlistRouteImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdlistsRoute = AdlistsRouteImport.update({
  id: '/adlists',
  path: '/adlists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIpStatsRoute = ClientsClientIpStatsRouteImport.update({
  id: '/$clientIp/stats',
  path: '/$clientIp/stats',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adlists': typeof AdlistsRoute
  '/allowlist': typeof AllowlistRoute
  '/api-keys': typeof ApiKeysRoute
  '/block-page-settings': typeof BlockPageSettingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/disable': typeof DisableRoute
  '/domains': typeof DomainsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/local-dns': typeof LocalDnsRoute
  '/login': typeof LoginRoute
  '/long-term': typeof LongTermRoute
  '/queries': typeof QueriesRoute
  '/regex-filters': typeof RegexFiltersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tools': typeof ToolsRoute
  '/ui-components': typeof UiComponentsRoute
  '/zones': typeof ZonesRoute
  '/clients/$clientIp/stats': typeof ClientsClientIpStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adlists': typeof AdlistsRoute
  '/allowlist': typeof AllowlistRoute
  '/api-keys': typeof ApiKeysRoute
  '/block-page-settings': typeof BlockPageSettingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/disable': typeof DisableRoute
  '/domains': typeof DomainsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/local-dns': typeof LocalDnsRoute
  '/login': typeof LoginRoute
  '/long-term': typeof LongTermRoute
  '/queries': typeof QueriesRoute
  '/regex-filters': typeof RegexFiltersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tools': typeof ToolsRoute
  '/ui-components': typeof UiComponentsRoute
  '/zones': typeof ZonesRoute
  '/clients/$clientIp/stats': typeof ClientsClientIpStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adlists': typeof AdlistsRoute
  '/allowlist': typeof AllowlistRoute
  '/api-keys': typeof ApiKeysRoute
  '/block-page-settings': typeof BlockPageSettingsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/disable': typeof DisableRoute
  '/domains': typeof DomainsRoute
  '/groups': typeof GroupsRoute
  '/health': typeof HealthRoute
  '/local-dns': typeof LocalDnsRoute
  '/login': typeof LoginRoute
  '/long-term': typeof LongTermRoute
  '/queries': typeof QueriesRoute
  '/regex-filters': typeof RegexFiltersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tools': typeof ToolsRoute
  '/ui-components': typeof UiComponentsRoute
  '/zones': typeof ZonesRoute
  '/clients/$clientIp/stats': typeof ClientsClientIpStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adlists'
    | '/allowlist'
    | '/api-keys'
    | '/block-page-settings'
    | '/clients'
    | '/disable'
    | '/domains'
    | '/groups'
    | '/health'
    | '/local-dns'
    | '/login'
    | '/long-term'
    | '/queries'
    | '/regex-filters'
    | '/settings'
    | '/setup'
    | '/tools'
    | '/ui-components'
    | '/zones'
    | '/clients/$clientIp/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adlists'
    | '/allowlist'
    | '/api-keys'
    | '/block-page-settings'
    | '/clients'
    | '/disable'
    | '/domains'
    | '/groups'
    | '/health'
    | '/local-dns'
    | '/login'
    | '/long-term'
    | '/queries'
    | '/regex-filters'
    | '/settings'
    | '/setup'
    | '/tools'
    | '/ui-components'
    | '/zones'
    | '/clients/$clientIp/stats'
  id:
    | '__root__'
    | '/'
    | '/adlists'
    | '/allowlist'
    | '/api-keys'
    | '/block-page-settings'
    | '/clients'
    | '/disable'
    | '/domains'
    | '/groups'
    | '/health'
    | '/local-dns'
    | '/login'
    | '/long-term'
    | '/queries'
    | '/regex-filters'
    | '/settings'
    | '/setup'
    | '/tools'
    | '/ui-components'
    | '/zones'
    | '/clients/$clientIp/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdlistsRoute: typeof AdlistsRoute
  AllowlistRoute: typeof AllowlistRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BlockPageSettingsRoute: typeof BlockPageSettingsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DisableRoute: typeof DisableRoute
  DomainsRoute: typeof DomainsRoute
  GroupsRoute: typeof GroupsRoute
  HealthRoute: typeof HealthRoute
  LocalDnsRoute: typeof LocalDnsRoute
  LoginRoute: typeof LoginRoute
  LongTermRoute: typeof LongTermRoute
  QueriesRoute: typeof QueriesRoute
  RegexFiltersRoute: typeof RegexFiltersRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ToolsRoute: typeof ToolsRoute
  UiComponentsRoute: typeof UiComponentsRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-components': {
      id: '/ui-components'
      path: '/ui-components'
      fullPath: '/ui-components'
      preLoaderRoute: typeof UiComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-filters': {
      id: '/regex-filters'
      path: '/regex-filters'
      fullPath: '/regex-filters'
      preLoaderRoute: typeof RegexFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/long-term': {
      id: '/long-term'
      path: '/long-term'
      fullPath: '/long-term'
      preLoaderRoute: typeof LongTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-dns': {
      id: '/local-dns'
      path: '/local-dns'
      fullPath: '/local-dns'
      preLoaderRoute: typeof LocalDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disable': {
      id: '/disable'
      path: '/disable'
      fullPath: '/disable'
      preLoaderRoute: typeof DisableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block-page-settings': {
      id: '/block-page-settings'
      path: '/block-page-settings'
      fullPath: '/block-page-settings'
      preLoaderRoute: typeof BlockPageSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowlist': {
      id: '/allowlist'
      path: '/allowlist'
      fullPath: '/allowlist'
      preLoaderRoute: typeof AllowlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adlists': {
      id: '/adlists'
      path: '/adlists'
      fullPath: '/adlists'
      preLoaderRoute: typeof AdlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientIp/stats': {
      id: '/clients/$clientIp/stats'
      path: '/$clientIp/stats'
      fullPath: '/clients/$clientIp/stats'
      preLoaderRoute: typeof ClientsClientIpStatsRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIpStatsRoute: typeof ClientsClientIpStatsRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIpStatsRoute: ClientsClientIpStatsRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdlistsRoute: AdlistsRoute,
  AllowlistRoute: AllowlistRoute,
  ApiKeysRoute: ApiKeysRoute,
  BlockPageSettingsRoute: BlockPageSettingsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DisableRoute: DisableRoute,
  DomainsRoute: DomainsRoute,
  GroupsRoute: GroupsRoute,
  HealthRoute: HealthRoute,
  LocalDnsRoute: LocalDnsRoute,
  LoginRoute: LoginRoute,
  LongTermRoute: LongTermRoute,
  QueriesRoute: QueriesRoute,
  RegexFiltersRoute: RegexFiltersRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ToolsRoute: ToolsRoute,
  UiComponentsRoute: UiComponentsRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
